### PR TITLE
Switch 10.2 and 10.3 to stretch

### PR DESCRIPTION
**Pull request by tianon**
https://github.com/docker-library/official-images/pull/2976#issuecomment-303518664

### CODE REVIEW

**Comment by tianon** [comment]
Two problems, one easy to solve, one not so easy:

- no `gpg` in stretch (easy to install)
- `E: Unable to locate package percona-xtrabackup` (package not available for `stretch`)

**Comment by tianon** [comment]
ala, https://repo.percona.com/apt/pool/main/p/percona-xtrabackup/

**Comment by tianon** [comment]
Kind of thinking that maybe now's the time to get rid of `percona-xtrabackup` again (at least for 10.2+), since it isn't actually used by the default install, and leave that as an exercise for the user.

**Comment by tianon** [comment]
It _is_ still recommended as the "only non-locking method" for SST on https://mariadb.com/kb/en/mariadb/getting-started-with-mariadb-galera-cluster/ however: :disappointed:

> This method uses the xtrabackup open-source hot backup utility to perform snapshot state transfers. It is the only non-locking method however it requires some additional setup.

**Comment by tianon** [comment]
@tanji would you mind lending us your opinion WRT `xtrabackup` and/or whether `stretch` is something we ought to move to now or wait until it's officially released? :pray: :innocent:

The rationale is that `stretch` is in freeze now, and should be released "soon", but won't see any really major changes, so should be a pretty stable base at this point (and we can't really update further down the line, so right now while 10.2 is transitioning to Stable and thus `latest` seems like a good time to consider it).

Does it make sense for the default install to include `xtrabackup`?  Should there be a separate install that includes it?  Should it be excluded completely and left up to users to figure out? (since it requires additional setup anyhow, and `rsync` is officially recommended)

Any thoughts/opinions you're willing to share would be :heart: :heart: :heart:

**Comment by tanji** [comment]
Hey @tianon, for some reason I thought that Docker official images were defaulting to Ubuntu. I might have been wrong :) I see some value in having `xtrabackup` in the base image as Galera clusters are commonplace nowadays, and even if `rsync` is the recommended method, most people use `xtrabackup` since it's non-locking.

To be honest, you might have not heard of it yet but it might be worth looking at [MariaDB Backup](https://mariadb.com/kb/en/mariadb/mariadb-backup/), which is MariaDB's fork of Xtrabackup that supports all the MariaDB features such as compression and encryption. Whether they have a package for `stretch` yet I do not know, but I can find out.

**Comment by tianon** [comment]
Ooh, officially supported fork by MariaDB is ++++++ even better IMO -- that doc only mentions 10.1.23, but I'm guessing this is probably even more mature for 10.2/10.3? :innocent:

**Comment by tianon** [comment]
Ah, looks like packages for it don't even exist in 10.2 yet -- would we just use the 10.1 version (`mariadb-backup-10.1_10.1.23+maria-1~stretch_amd64.deb	`) against 10.2, or do we need to wait for 10.2 to be supported?

http://ftp.osuosl.org/pub/mariadb/repo/10.1/debian/pool/main/m/mariadb-10.1/
vs
http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/pool/main/m/mariadb-10.2/

**Comment by tanji** [comment]
Well, for some reason (even if 10.2 is GA today) it seems that `mariadbbackup` is not yet in the 10.2 repository, however you can find it [here](http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.1/debian/pool/main/m/mariadb-10.1/) including a `stretch` version. I'll check with the developers at MariaDB whenever they plan to release `mariadbbackup` for 10.2/stretch and let you know :)

**Comment by tanji** [comment]
I have no idea if the 10.1 version works with 10.2 (it theoretically should. The xtrabackup version we've all used was historically built against MySQL 5.6). But I intend to find out!

**Comment by tianon** [comment]
Any news on this front, @tanji? :pray: :innocent: :heart:

**Comment by tanji** [comment]
I see no mariabackup for 10.2 in the repos yet, I'll ask directly!

**Comment by tanji** [comment]
Answer: `mariabackup` for MariaDB 10.2 is a tight case, because MariaDB 10.2 comes with a new version of InnoDB, therefore some parts have to be rewritten. It might come out with the next 10.2 release (10.2.7).

**Comment by denji** [comment]
thks for the broken release 10.2+ (`:latest`) with a minimal preinstall plugins, 10.1 which does not break backward compatibility.

**Comment by tanji** [comment]
Still no news of `mariabackup` for MariaDB 10.2 and above. But with the PR you merged, I suppose we can use `xtrabackup` in the meantime.

**Comment by tanji** [comment]
@tianon, Finally !
mariadb-backup is out for 10.2/stretch. Please check the repo.

**Comment by klausenbusk** [comment]
> To be honest, you might have not heard of it yet but it might be worth looking at MariaDB Backup, which is MariaDB's fork of Xtrabackup that supports all the MariaDB features such as compression and encryption.

This will break any Galera cluster which use `xtrabackup` as the [SST](http://galeracluster.com/documentation-webpages/statetransfer.html) method. If you decide to switch to `mariabackup`, we at least need to warn the users or create a symlink (`xtrabackup` -> `mariabackup`)?

**Comment by Renkas** [comment]
So whats happening here? mariabackup is not available in the 10.2.11 image. I thought it comes by default since 10.2.10.

**Comment by iangilfillan** [comment]
Note that https://mariadb.com/kb/en/library/getting-started-with-mariadb-galera-cluster/ which is referenced above has been updated and now refers to mariabackup

**Comment by xcompass** [comment]
after reading the this PR, I still don't understand why mariabackup is not included in the container instead of xtrabackup.

**Comment by klausenbusk** [comment]
> I still don't understand why mariabackup is not included in the container instead of xtrabackup.

It would break existing Galera setup which use xtrabackup for SST.

**Comment by xcompass** [comment]
> It would break existing Galera setup which use xtrabackup for SST.

Thanks. But can we include both? Are they conflict with each other?

**Comment by klausenbusk** [comment]
> Thanks. But can we include both? Are they conflict with each other?

I just tested it, installing `mariadb-backup-10.1` (from MariaDB repo) and `percona-xtrabackup-24` (from Percona repo) in a Debian Stretch container does not yield any error.

**Comment by klausenbusk** [comment]
So I just spent some time trying to replace xtrabackup with mariabackup without breaking existing setup and fixing everything else mentioned in the PR.

Feel free to check it out: https://github.com/docker-library/mariadb/pull/158

**Pull request closed without merging**
