### PR TITLE
Make tzinfo opt-in.

### PR DESCRIPTION
**Pull request by klausenbusk**
Not sure if it should be opt-in or opt-out, also a little unsure about the env name `MYSQL_LOAD_TIME_ZONE_TABLES`. I think it should be opt-in.
#24 depends on this.

### CODE REVIEW

**Comment by md5** [comment]
Seems like this needs to be an opt-out to avoid breaking existing users who are now relying on the DB having the time zones loaded. I know I personally ran into this with the `mysql` image one some point. I didn't find any user reports that motivated https://github.com/docker-library/mysql/pull/80, but I seem to recall that there were some.

**Comment by klausenbusk** [comment]
How do this look?

**Comment by md5** [comment]
LGTM. Let's see what the maintainers have to say.

**Comment by klausenbusk** [comment]
Any update?

**Comment by klausenbusk** [comment]
Update?

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
I like the feature, but I'm not so sure about the name. :confused:

I'm thinking maybe something slightly more descriptive of exactly what's being skipped, like `MYSQL_INITDB_SKIP_TZINFO`.  WDYT?

**Comment by klausenbusk** [comment]
> but I'm not so sure about the name.

Me either. 


> I'm thinking maybe something slightly more descriptive of exactly what's being skipped, like MYSQL_INITDB_SKIP_TZINFO. WDYT?

Look fine to me, I can update the PR now, if it okay?

**Comment by tianon** [comment]
Yeah, sounds good enough; thanks for bearing with us. :+1:

**Comment by klausenbusk** [comment]
Done, also not sure about the commit message. Maybe it fine.

**Comment by tianon** [comment]
`¯\_(ツ)_/¯`

LGTM

**Comment by yosifkit** [comment]
Commit message seems fine.

**Pull request merged**
