### PR TITLE
Add 10.2, including a "development" tag (to hopefully make it clear this is the "development release", not stable)

### LINKED ISSUE #98: Docker image for 10.2.3
How long until you get a docker image for 10.2 into the docker repository?

### PR DESCRIPTION
**Pull request by tianon**
fixes #98

### CODE REVIEW

**Comment by yosifkit** [comment]
`development` has the "follows the development git branch" connotation; maybe `alpha` is better: https://downloads.mariadb.org/mariadb/10.2.1/?

Maybe we just need big warnings on the docs page?

**Comment by tianon** [comment]
I wanted `alpha` originally, but that's going to change to `beta` at some point and unless we're watching really diligently, we won't notice the change (see https://mariadb.com/kb/en/mariadb/what-is-mariadb-101/#list-of-all-mariadb-101-releases -- 10.1.2 was Alpha but 10.1.3 was Beta and 10.1.7 was RC).  If there's an easy way for `generate-stackbrew-library.sh` to determine `alpha`/`beta`/etc. status for a given release version in an automated way, I'm definitely very +1 to using `alpha` instead.

**Comment by tianon** [comment]
I wonder if there's a more machine-friendly version of https://downloads.mariadb.org/mariadb/+releases/ somewhere.

**Comment by yosifkit** [comment]
Not sure about a machine readable version, but here is a fragile sample parser of the current page:
```bash
version=10.2; curl -fsSL https://downloads.mariadb.org/mariadb/+releases/ \
| awk '{ 
    if (match($0, /mariadb\/('"$version"'[^\/]*)\//, ver)) { c=1; print ver[1] }
    if (c==1) {
        if (match($0, /.*td>([A-Za-z ]+)<\/td.*/, ary)) { print ary[1] };
        if (/\/tr/) c=0
    } 
}'
```

**Comment by yosifkit** [comment]
So my more complete idea is to use the `awk` in `update.sh` (which is where our hacky html sed/awk parsing usually lives) and have it make or delete a `variant` file that would tell us if that version is `alpha`, `beta`, or `rc`.  Then `generate-stackbrew` just checks for a `variant` file and uses that in the tag generation.

**Comment by tianon** [comment]
https://downloads.mariadb.org/mariadb/+releases/ -- 10.2 is now in Release Candidates stages, and 10.3.0 is Alpha

I'm thinking maybe we should simply give up on aliases for now and link to the "releases" page directly (and leave it up to users to figure out what's what).  Sound fair?

(Then we only maintain `latest` pointing to the latest non-pre-release.)

**Comment by tianon** [comment]
Updated what what I've proposed (and included 10.3).

**Comment by denji** [comment]
MariaDB 10.2 made template updates without checking for regressive testing.
`mariadb:10.2` TokuDB not installed plugin,  `mariadb:10.1` TokuDB just work fine

```diff
	&& apt-get install -y \
		mariadb-server=$MARIADB_VERSION \
+		mariadb-plugin-aws-key-management-10.2=$MARIADB_VERSION \
+		mariadb-plugin-connect=$MARIADB_VERSION \
+		mariadb-plugin-cracklib-password-check=$MARIADB_VERSION \
+		mariadb-plugin-gssapi-client=$MARIADB_VERSION \
+		mariadb-plugin-gssapi-server=$MARIADB_VERSION \
+		mariadb-plugin-mroonga=$MARIADB_VERSION \
+		mariadb-plugin-oqgraph=$MARIADB_VERSION \
+		mariadb-plugin-rocksdb=$MARIADB_VERSION \
+		mariadb-plugin-spider=$MARIADB_VERSION \
+		mariadb-plugin-tokudb=$MARIADB_VERSION \
```

**Pull request merged**
