### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by todstoychev**
Fixing TERM environment variable not set error. I tried this locally and it works for me. Test and merge if you like it.

### CODE REVIEW

**Comment by tianon** [comment]
Can you elaborate a bit more on what the error was that this fixes?  I can't seem to duplicate any problems not having it set. :confused:

**Comment by tanji** [comment]
I assume it fixes this issue:
```
$ docker exec -ti compose_db2_1 /bin/bash                      
root@ade02a7896f3:/# mysql -padmin
TERM environment variable not set.
```

**Comment by todstoychev** [comment]
It fixes an error with variable TERM not set. It appears when you try to login to the dabase server with 'mysql -u root -p' for example. I have an image build with this dockerfile and it seems to work and not producing errors.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.3.8&pv=4.4.4&source=email_footer_2] On Sat, Apr 23, 2016 at 3:16 AM, Tianon Gravi < notifications@github.com [notifications@github.com] > wrote:
Can you elaborate a bit more on what the error was that this fixes? I can't seem to duplicate any problems not having it set.

**Comment by tianon** [comment]
Sorry for the long delay :disappointed:

I think this looks like it's probably due to https://github.com/docker/docker/issues/9299, which was fixed in https://github.com/docker/docker/pull/26461, and released in Docker 1.13+. :+1: :heart:

**Comment by tianon** [comment]
To illustrate (running Docker 17.03.0-ce locally):
```console
$ docker run -dit --name test -e MYSQL_ROOT_PASSWORD=example mariadb
b207b61b7efc13524e1da50bce009d4b071569d6db74c619f56539699c06b325
$ docker exec -it test bash
root@b207b61b7efc:/# mysql -uroot -pexample
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.22-MariaDB-1~jessie mariadb.org binary distribution

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 
```

**Pull request closed without merging**
