### PR TITLE
Adding update procedure on startup

### PR DESCRIPTION
**Pull request by flavioaiello**
The entrypoint is responsible for database initialization in case no database is provided, thus it would make sense to be responsible for the database upgrade as well.

### CODE REVIEW

**Comment by tianon** [comment]
I agree in theory, but in practice this implementation is going to be quite a drain on users' systems -- I think we instead need to do something similar to https://github.com/docker-library/mysql/pull/416 (and frankly, I'd rather resolve that one first and copy the implementation here afterwards unless there's a compelling reason why MariaDB would have a differing implementation).

**Comment by flavioaiello** [comment]
I fully agree that both engine variants could and should be solved in the same manner. But why checking version etc. with shell scripting if the update process is able to do same by itself?

**Comment by tianon** [comment]
Because it avoids starting up `mysqld` unnecessarily, which is pretty heavy.

**Comment by CReimer** [comment]
The issue for MySQL got closed. MySQL seems to do something like mysql_upgrade by itself on startup.

Any chance something like this gets adopted by MariaDB anytime soon?

**Comment by J0WI** [comment]
https://jira.mariadb.org/browse/MDEV-9394

**Comment by tianon** [comment]
Closing in favor of https://jira.mariadb.org/browse/MDEV-9394 -- this is too heavy for us to do by default (starting `mysqld` twice on *every* container startup).

See also https://github.com/docker-library/mariadb/pull/271, which made implementing these types of customizations in a descendent image much easier to accomplish in a reliable/maintainable way.

**Pull request closed without merging**
