### PR TITLE
Add initial .travis.yml

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Simple, fast builds. :+1:

**Comment by thaJeztah** [comment]
Ooooh, tests for the official images? :heart:

**Comment by tianon** [comment]
@thaJeztah yeah, the tests live in the official-images repo, but now we're previewing some in-progress Travis features to let us actually run them on each PR to these satellite repos too :+1:

**Comment by thaJeztah** [comment]
@tianon sounds great `!m tianon`

Wot?

No bot?

😢

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
