### PR TITLE
Fixed not passing options on first run.

### PR DESCRIPTION
**Pull request by klausenbusk**
I need this for my Galera Dockerfile, which use this image as a derived image. I need it so I can pass --wsrep-new-cluster and --wsrep_cluster_address..

### CODE REVIEW

**Comment by klausenbusk** [comment]
A little too fast.

**Comment by yosifkit** [comment]
This looks like a good idea to me.  Once we get it merged, we should look to replicate the change to `mysql` and `percona` images.

**Comment by klausenbusk** [comment]
> This looks like a good idea to me. Once we get it merged, we should look to replicate the change to mysql and percona images.

Forgot to update the template file. What is we waiting on? :)

**Comment by tianon** [comment]
Yeah, seems fine, although replicating it to both `mysql` and `percona` is definitely a good idea (since they all share this same script).

**Pull request merged**
